---
title: "modelToolKitGuide"
author: "Matthew Davis"
date: "August 4, 2017"
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
Get predictive model prefomance by a catagory
```{r setup, message=FALSE, comment=''}
try(detach(package:modelToolKit, unload = TRUE))
library(modelToolKit)
library(rpart)
data(iris)
set.seed(2012)
fit<-rpart(Species~., iris)
km<-kmeans(iris[,1:4], 3)
preds<-predict(fit, iris, type = 'class')
obs<-iris[,'Species']
cats<-as.factor(km$cluster)
preformanceByCatagory(preds, obs, cats)

```

Assign new clusters using kmeans to new data 

```{r }
head(predictKmeans(km, iris))
```

Find differences between data frames
```{r}

find2dfDiffs(iris[,1:4],iris[, 1:4]+.12)
```
Find the optimal number of clusters
```{r, }
findClusters(iris[,1:4])
```

Find differences between two factors 
```{r}
set.seed(12012)
x = as.factor(rep(c('a','b','c' , 'a'), 10))
y = as.factor(sample(c('a','b','c'), 30, replace = TRUE))
z<-factorDiffs(x,y)


```

Find differencew between all factors in two data frames
```{r}
size = 100
df1<-data.frame(x = as.factor(sample(c('a','b','c' ,'d'),size, replace = TRUE)),
                y = as.factor(sample(c('a','b','c','a') ,size, replace = TRUE)))

df2<-data.frame(x = as.factor(sample(c('a','b','c','c'),size, replace = TRUE)),
                y = as.factor(sample(c('a','b','c','b'), size, replace = TRUE)))

dataFrameFactDiffs(df1, df2)
```



```{r}
mydata<-data.frame(fact1 = as.factor(rep(c('a','a','c', NA), 1000)), 
                  fact2 = as.factor(rep(c('e','e','g','h'), 1000)))
mydata1<-data.frame(fact1 = as.factor(rep(c('a','b b','F' ,NA), 1000)), 
                  fact2 = as.factor(rep(c('k','f','g','h'), 1000)))

dmv<-dummyVars(~., mydata)
str(mydata)
str(levelMatcher(dmv, newData = mydata1))
str(levelMatcher(newData = mydata1, oldData = mydata))
```                


